### ISSUE TITLE
Attempt to add logos have resulted in: Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by Aceboone011** [solana-labs/token-list#10721]
- **I'm submitting a ...**
  [ x] bug report
  [] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**  
- Hey I've been trying to patch my logo and change my symbol. I keep getting the same error:
-   1 test failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "test:unit" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

Eerything is up to date, the repos was forked,
I tried to delete the auto-created "yarn.lock" file for a merge attempt at fixing it, and that was a fail as well. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment]
please link a PR

**Comment by keone** [comment]
if youre talking about this one: https://github.com/solana-labs/token-list/pull/10720
the error in https://github.com/solana-labs/token-list/runs/4632956774?check_suite_focus=true
is
```
  Token list does not have duplicate entries
```

because you're re-adding `55EZVKbY9u9vdouob88QiKQ4g9nfYUoAu7aWQUiuQ8pc` which you already added; look at this diff: https://github.com/solana-labs/token-list/pull/10720/files

**Comment by sombeProject** [comment]
@keone How to fix this issue   "Token list does not have duplicate entries" ?

Thank you
