### ISSUE TITLE
Vladimir vs volodymyr token info Build #28207  ( Still haven not got any reply )

### ISSUE THREAD

**Issue by cariocc** [solana-labs/token-list#21242]
Having problem with pushing my token name update , running into automerge build issue . RUN YARN TEST 

Error: Process completed with exit code 1.

**Comment by cariocc** [comment]
> what's your PR?

#20664 opened 7 days ago by [cariocc](https://github.com/solana-labs/token-list/issues?q=is%3Apr+is%3Aopen+author%3Acariocc)

**Comment by cariocc** [comment]
> what's your PR?

Trying to find solution for days already... Not so familiar with github as well but already tried everything i could by running commands on dekstop version etc. (maybe even messed up it more)

**Comment by spacemandev-git** [comment]
This PR has two problems

1. Duplicate token: https://github.com/solana-labs/token-list#duplicate-token (you already added this token and should edit the existing token you added rather than creating it again)
2. you edited vscode settings file, which you shouldn't touch

try again with a fresh copy of the solana token list repo. find your vvv token and edit it only instead of adding it again at the end.
