### ISSUE TITLE
logo replace TruSwap token

### ISSUE THREAD

**Issue by Msaqib0786** [solana-labs/token-list#23332]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Msaqib0786** [comment]
https://github.com/solana-labs/token-list/pull/23331

Sir allow to eligible for change plz

https://github.com/merged

@willsmythe

**Comment by spacemandev-git** [comment]
the logo was already merged. merged means the solana token list is updated. if you're complaining because it's not showing up in the wallet/whatever service you're using, it's because that service has not pulled the most recent changes from the solana token list. different services pull changes at different intervals.
